//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSTABLE
    {
        public string user_table { get; set; }
        public string student_table { get; set; }
        public string guardian_table { get; set; }
        public string teacher_table { get; set; }
        public string class_table { get; set; }
        public string section_table { get; set; }
        public string attendance_table { get; set; }
    }
}
